import * as cdk from 'aws-cdk-lib';
import * as appscaling from 'aws-cdk-lib/aws-applicationautoscaling';
import * as budgets from 'aws-cdk-lib/aws-budgets';
import * as cloudwatch from 'aws-cdk-lib/aws-cloudwatch';
import * as cloudwatchActions from 'aws-cdk-lib/aws-cloudwatch-actions';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import * as events from 'aws-cdk-lib/aws-events';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as kms from 'aws-cdk-lib/aws-kms';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import * as sns from 'aws-cdk-lib/aws-sns';
import * as sqs from 'aws-cdk-lib/aws-sqs';
import * as sfn from 'aws-cdk-lib/aws-stepfunctions';
import * as tasks from 'aws-cdk-lib/aws-stepfunctions-tasks';
import { Construct } from 'constructs';
import type { PolycastMediaBuckets } from './polycast-api-stack';
import {
  POLYCAST_CHILD_STATE_MACHINE_NAME,
  POLYCAST_EVENT_BUS_NAME,
  POLYCAST_PARENT_STATE_MACHINE_NAME,
  tagPolycastStack,
  polycastContainerImage,
} from './polycast-common';
import { TARGET_STAGES, TargetStage } from './stage-table';

export interface PolycastOrchestrationStackProps extends cdk.StackProps {
  vpc: ec2.IVpc;
  /** ECS cluster shared with the API stack. */
  cluster: ecs.ICluster;
  encryptionKey: kms.IKey;
  buckets: PolycastMediaBuckets;
  /** `http://<internal api alb dns>`: the worker's `--api-url`. */
  apiUrl: string;
  /** Security group of the API's internal ALB; this stack adds the worker's ingress rule. */
  apiLoadBalancerSecurityGroup: ec2.ISecurityGroup;
  /** WORKER_TOKEN generated by PolycastApi. */
  workerTokenSecret: secretsmanager.ISecret;
  /** ECR image tag to run; defaults to `latest`. */
  /**
   * Verified SES sender for email notifications (`SES_FROM_ADDRESS`). When omitted the worker
   * records notifications in-app only (services/media-worker config).
   */
  sesFromAddress?: string;
  /**
   * Lip-sync vendor for the worker (`LIP_SYNC_PROVIDER`): `mock` (default, lip sync reported
   * as not applied) or `synclabs` (sync.so; the API key must be stored in the
   * `polycast/synclabs` secret first, see docs/aws-setup.md).
   */
  lipSyncProvider?: 'mock' | 'synclabs';
  /** Monthly cost budget in USD; notifications at 80% and 100%. Defaults to 200. */
  monthlyBudgetUsd?: number;
}

/**
 * Media-plane orchestration (ADR-0004, architecture.md §4).
 *
 * State machines (Standard workflows, X-Ray on, ALL-level logs for 30 days):
 *
 * Parent `polycast-localization-job`, input
 *   { localizationJobId, organizationId, maxConcurrency, targets: [{ targetJobId, targetLocale, lipSync }] }
 *   TRANSCRIBING -> SOURCE_QA (Pass states in M2: analysis already ran before QUEUED)
 *   -> TARGETS_FAN_OUT (Map over $.targets, MaxConcurrencyPath $.maxConcurrency)
 *      each item starts the child synchronously with
 *      { targetJobId, targetLocale, lipSync, organizationId, localizationJobId }
 *   -> JOB_COMPLETE.
 *
 * Child `polycast-target-job`, one task-token state per entry of `TARGET_STAGES`:
 *   every stage sends { taskToken, stage, targetJobId, organizationId, attempt } to the stage
 *   queue and waits for `SendTaskSuccess`; the worker's output lands in `$.results.<STAGE>`
 *   (`$.qa` for TARGET_QA, expected to contain `needsReview`). Retry on States.TaskFailed /
 *   States.Timeout (30 s, x2, 3 attempts), then Catch -> `<STAGE>_FAILED`.
 *   LipSyncEnabled ($.lipSync == true) decides whether LIP_SYNCING runs; ReadyGate
 *   ($.qa.needsReview == true) inserts NEEDS_REVIEW, a task-token wait on the review-wait queue
 *   that the approve endpoint resolves (up to 365 days), before PACKAGING -> COMPLETE.
 *
 * The M1 worker still polls the API for tasks; the SQS queue is the M2 seam that the
 * StepFunctionsOrchestrator in the API bridges.
 */
export class PolycastOrchestrationStack extends cdk.Stack {
  public readonly eventBus: events.EventBus;
  public readonly stageQueue: sqs.Queue;
  public readonly stageDeadLetterQueue: sqs.Queue;
  public readonly reviewWaitQueue: sqs.Queue;
  public readonly childStateMachine: sfn.StateMachine;
  public readonly parentStateMachine: sfn.StateMachine;
  public readonly workerService: ecs.FargateService;
  public readonly syncLabsSecret: secretsmanager.Secret;
  public readonly alertsTopic: sns.Topic;

  constructor(scope: Construct, id: string, props: PolycastOrchestrationStackProps) {
    super(scope, id, props);
    tagPolycastStack(this, 'orchestration');

    const monthlyBudgetUsd = props.monthlyBudgetUsd ?? 200;

    this.alertsTopic = new sns.Topic(this, 'AlertsTopic', {
      displayName: 'Polycast alerts (alarms and budget)',
    });
    const alarmAction = new cloudwatchActions.SnsAction(this.alertsTopic);

    // ------------------------------------------------------------ bus + queues
    this.eventBus = new events.EventBus(this, 'Bus', { eventBusName: POLYCAST_EVENT_BUS_NAME });

    this.stageDeadLetterQueue = new sqs.Queue(this, 'StageDeadLetterQueue', {
      queueName: 'polycast-stage-dlq',
      retentionPeriod: cdk.Duration.days(14),
      encryption: sqs.QueueEncryption.KMS,
      encryptionMasterKey: props.encryptionKey,
      enforceSSL: true,
    });
    this.stageQueue = new sqs.Queue(this, 'StageQueue', {
      queueName: 'polycast-stage',
      retentionPeriod: cdk.Duration.days(14),
      visibilityTimeout: cdk.Duration.minutes(5),
      encryption: sqs.QueueEncryption.KMS,
      encryptionMasterKey: props.encryptionKey,
      enforceSSL: true,
      deadLetterQueue: { queue: this.stageDeadLetterQueue, maxReceiveCount: 3 },
    });
    this.reviewWaitQueue = new sqs.Queue(this, 'ReviewWaitQueue', {
      queueName: 'polycast-review-wait',
      retentionPeriod: cdk.Duration.days(14),
      visibilityTimeout: cdk.Duration.minutes(5),
      encryption: sqs.QueueEncryption.KMS,
      encryptionMasterKey: props.encryptionKey,
      enforceSSL: true,
    });

    // ------------------------------------------------------- child state machine
    const child = new Construct(this, 'TargetJob');
    const stageTask = (stage: TargetStage): tasks.SqsSendMessage => {
      const task = new tasks.SqsSendMessage(child, stage, {
        queue: this.stageQueue,
        integrationPattern: sfn.IntegrationPattern.WAIT_FOR_TASK_TOKEN,
        messageBody: sfn.TaskInput.fromObject({
          taskToken: sfn.JsonPath.taskToken,
          stage,
          targetJobId: sfn.JsonPath.stringAt('$.targetJobId'),
          organizationId: sfn.JsonPath.stringAt('$.organizationId'),
          attempt: sfn.JsonPath.numberAt(sfn.JsonPath.stateRetryCount),
        }),
        resultPath: stage === 'TARGET_QA' ? '$.qa' : `$.results.${stage}`,
        taskTimeout: sfn.Timeout.duration(cdk.Duration.hours(12)),
      });
      task.addRetry({
        errors: ['States.TaskFailed', 'States.Timeout'],
        interval: cdk.Duration.seconds(30),
        backoffRate: 2,
        maxAttempts: 3,
      });
      task.addCatch(
        new sfn.Fail(child, `${stage}_FAILED`, {
          error: `${stage}_FAILED`,
          cause: `Stage ${stage} failed after retries`,
        }),
        { errors: ['States.ALL'], resultPath: '$.error' },
      );
      return task;
    };
    const taskOf = Object.fromEntries(TARGET_STAGES.map((s) => [s, stageTask(s)])) as Record<
      TargetStage,
      tasks.SqsSendMessage
    >;

    const needsReview = new tasks.SqsSendMessage(child, 'NEEDS_REVIEW', {
      queue: this.reviewWaitQueue,
      integrationPattern: sfn.IntegrationPattern.WAIT_FOR_TASK_TOKEN,
      messageBody: sfn.TaskInput.fromObject({
        taskToken: sfn.JsonPath.taskToken,
        stage: 'NEEDS_REVIEW',
        targetJobId: sfn.JsonPath.stringAt('$.targetJobId'),
        organizationId: sfn.JsonPath.stringAt('$.organizationId'),
      }),
      resultPath: '$.review',
      taskTimeout: sfn.Timeout.duration(cdk.Duration.days(365)),
    });
    const complete = new sfn.Succeed(child, 'COMPLETE');

    // Successor of each stage, generated from the table so state names cannot drift.
    const successorOf = (stage: TargetStage): sfn.IChainable => {
      const index = TARGET_STAGES.indexOf(stage);
      const following = TARGET_STAGES[index + 1];
      if (following === undefined) return complete;
      if (following === 'LIP_SYNCING') {
        const afterLipSync = TARGET_STAGES[index + 2];
        if (afterLipSync === undefined) throw new Error('LIP_SYNCING cannot be the last stage');
        return new sfn.Choice(child, 'LipSyncEnabled')
          .when(sfn.Condition.booleanEquals('$.lipSync', true), taskOf.LIP_SYNCING)
          .otherwise(taskOf[afterLipSync]);
      }
      if (stage === 'TARGET_QA') {
        return new sfn.Choice(child, 'ReadyGate')
          .when(sfn.Condition.booleanEquals('$.qa.needsReview', true), needsReview)
          .otherwise(taskOf[following]);
      }
      return taskOf[following];
    };
    for (const stage of TARGET_STAGES) taskOf[stage].next(successorOf(stage));
    needsReview.next(taskOf.PACKAGING);

    this.childStateMachine = new sfn.StateMachine(this, 'TargetJobStateMachine', {
      stateMachineName: POLYCAST_CHILD_STATE_MACHINE_NAME,
      stateMachineType: sfn.StateMachineType.STANDARD,
      definitionBody: sfn.DefinitionBody.fromChainable(taskOf.TRANSLATING),
      timeout: cdk.Duration.days(366),
      tracingEnabled: true,
      logs: {
        destination: new logs.LogGroup(this, 'TargetJobLogs', {
          retention: logs.RetentionDays.ONE_MONTH,
          removalPolicy: cdk.RemovalPolicy.DESTROY,
        }),
        level: sfn.LogLevel.ALL,
        includeExecutionData: false, // ids only in the input, but keep content out by policy
      },
    });

    // ------------------------------------------------------ parent state machine
    const parent = new Construct(this, 'LocalizationJob');
    const transcribing = new sfn.Pass(parent, 'TRANSCRIBING', {
      comment:
        'Analysis (transcription, diarization) already ran before QUEUED; real Transcribe stage arrives in M3',
    });
    const sourceQa = new sfn.Pass(parent, 'SOURCE_QA', {
      comment: 'Source QA placeholder until M3 QC workers exist',
    });
    const fanOut = new sfn.Map(parent, 'TARGETS_FAN_OUT', {
      itemsPath: '$.targets',
      maxConcurrencyPath: '$.maxConcurrency',
      itemSelector: {
        localizationJobId: sfn.JsonPath.stringAt('$.localizationJobId'),
        organizationId: sfn.JsonPath.stringAt('$.organizationId'),
        targetJobId: sfn.JsonPath.stringAt('$$.Map.Item.Value.targetJobId'),
        targetLocale: sfn.JsonPath.stringAt('$$.Map.Item.Value.targetLocale'),
        lipSync: sfn.JsonPath.objectAt('$$.Map.Item.Value.lipSync'),
      },
      resultPath: '$.targetResults',
    });
    fanOut.itemProcessor(
      new tasks.StepFunctionsStartExecution(parent, 'RunTargetJob', {
        stateMachine: this.childStateMachine,
        integrationPattern: sfn.IntegrationPattern.RUN_JOB,
        input: sfn.TaskInput.fromJsonPathAt('$'),
        name: sfn.JsonPath.format(
          '{}-{}',
          sfn.JsonPath.stringAt('$.targetJobId'),
          sfn.JsonPath.stringAt('$$.Execution.Name'),
        ),
      }),
    );
    const jobComplete = new sfn.Succeed(parent, 'JOB_COMPLETE');

    this.parentStateMachine = new sfn.StateMachine(this, 'LocalizationJobStateMachine', {
      stateMachineName: POLYCAST_PARENT_STATE_MACHINE_NAME,
      stateMachineType: sfn.StateMachineType.STANDARD,
      definitionBody: sfn.DefinitionBody.fromChainable(
        transcribing.next(sourceQa).next(fanOut).next(jobComplete),
      ),
      timeout: cdk.Duration.days(366),
      tracingEnabled: true,
      logs: {
        destination: new logs.LogGroup(this, 'LocalizationJobLogs', {
          retention: logs.RetentionDays.ONE_MONTH,
          removalPolicy: cdk.RemovalPolicy.DESTROY,
        }),
        level: sfn.LogLevel.ALL,
        includeExecutionData: false,
      },
    });

    // ------------------------------------------------------------- media worker

    const workerTaskRole = new iam.Role(this, 'WorkerTaskRole', {
      assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
      description: 'Polycast media worker: media buckets, stage queues, task-token callbacks',
    });
    for (const bucket of Object.values(props.buckets)) bucket.grantReadWrite(workerTaskRole);
    props.encryptionKey.grantEncryptDecrypt(workerTaskRole);
    this.stageQueue.grantConsumeMessages(workerTaskRole);
    this.reviewWaitQueue.grantConsumeMessages(workerTaskRole);
    workerTaskRole.addToPolicy(
      new iam.PolicyStatement({
        sid: 'ResolveTaskTokens',
        actions: ['states:SendTaskSuccess', 'states:SendTaskFailure', 'states:SendTaskHeartbeat'],
        resources: ['*'],
      }),
    );
    // The provider adapters (services/media-worker/polycast_worker/providers/aws). These APIs
    // are not resource-scoped: Transcribe and Polly jobs are named per task, Translate and
    // Bedrock take text, and Transcribe reads/writes the media buckets with this role's own
    // S3 and KMS permissions (no data-access role is configured).
    workerTaskRole.addToPolicy(
      new iam.PolicyStatement({
        sid: 'ProviderApis',
        actions: [
          'transcribe:StartTranscriptionJob',
          'transcribe:GetTranscriptionJob',
          'translate:TranslateText',
          'polly:DescribeVoices',
          'polly:SynthesizeSpeech',
          'bedrock:InvokeModel',
          'bedrock:InvokeModelWithResponseStream',
          'mediaconvert:DescribeEndpoints',
          'mediaconvert:CreateJob',
          'mediaconvert:GetJob',
          'ses:SendEmail',
        ],
        resources: ['*'],
      }),
    );

    // Third-party lip-sync credentials. Created with an empty key so the deploy never carries
    // a real value; the owner pastes the vendor key into this secret (field `apiKey`) in the
    // console or CLI, then redeploys with lipSyncProvider=synclabs. The worker refuses to start
    // with `synclabs` selected and an empty key (config.py fails closed).
    this.syncLabsSecret = new secretsmanager.Secret(this, 'SyncLabsApiKey', {
      secretName: 'polycast/synclabs',
      description: 'Polycast: sync.so API key for the lip-sync provider (field apiKey)',
      secretObjectValue: { apiKey: cdk.SecretValue.unsafePlainText('') },
    });

    const workerTaskDefinition = new ecs.FargateTaskDefinition(this, 'WorkerTaskDefinition', {
      cpu: 1024,
      memoryLimitMiB: 2048,
      taskRole: workerTaskRole,
      runtimePlatform: {
        cpuArchitecture: ecs.CpuArchitecture.X86_64,
        operatingSystemFamily: ecs.OperatingSystemFamily.LINUX,
      },
    });
    workerTaskDefinition.addContainer('media-worker', {
      image: polycastContainerImage(this, 'WorkerImage', 'services/media-worker/Dockerfile'),
      command: ['python', '-m', 'polycast_worker', '--api-url', props.apiUrl],
      environment: {
        POLYCAST_ENV: 'production',
        PROVIDER_MODE: 'aws',
        STORAGE_DRIVER: 's3',
        AWS_REGION: this.region,
        API_BASE_URL: props.apiUrl,
        WORKER_QUEUE_URL: this.stageQueue.queueUrl,
        MEDIA_BUCKET_QUARANTINE: props.buckets.quarantine.bucketName,
        MEDIA_BUCKET_SOURCE: props.buckets.source.bucketName,
        MEDIA_BUCKET_DERIVED: props.buckets.derived.bucketName,
        MEDIA_BUCKET_DELIVERABLES: props.buckets.deliverables.bucketName,
        ...(props.sesFromAddress ? { SES_FROM_ADDRESS: props.sesFromAddress } : {}),
        LIP_SYNC_PROVIDER: props.lipSyncProvider ?? 'mock',
      },
      secrets: {
        WORKER_TOKEN: ecs.Secret.fromSecretsManager(props.workerTokenSecret),
        SYNCLABS_API_KEY: ecs.Secret.fromSecretsManager(this.syncLabsSecret, 'apiKey'),
      },
      logging: ecs.LogDrivers.awsLogs({
        streamPrefix: 'media-worker',
        logGroup: new logs.LogGroup(this, 'WorkerLogs', {
          retention: logs.RetentionDays.ONE_MONTH,
          removalPolicy: cdk.RemovalPolicy.DESTROY,
        }),
      }),
    });

    const workerSecurityGroup = new ec2.SecurityGroup(this, 'WorkerSecurityGroup', {
      vpc: props.vpc,
      description: 'Polycast media worker tasks',
      allowAllOutbound: true,
    });
    this.workerService = new ecs.FargateService(this, 'WorkerService', {
      cluster: props.cluster,
      serviceName: 'polycast-media-worker',
      taskDefinition: workerTaskDefinition,
      desiredCount: 1,
      minHealthyPercent: 0,
      maxHealthyPercent: 200,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      securityGroups: [workerSecurityGroup],
      circuitBreaker: { rollback: true },
    });
    props.apiLoadBalancerSecurityGroup.addIngressRule(
      workerSecurityGroup,
      ec2.Port.tcp(80),
      'Polycast media worker to API internal ALB (/internal/v1)',
      true,
    );
    const workerScaling = this.workerService.autoScaleTaskCount({ minCapacity: 1, maxCapacity: 4 });
    workerScaling.scaleOnMetric('QueueDepth', {
      metric: this.stageQueue.metricApproximateNumberOfMessagesVisible({
        period: cdk.Duration.minutes(1),
        statistic: 'Maximum',
      }),
      adjustmentType: appscaling.AdjustmentType.CHANGE_IN_CAPACITY,
      cooldown: cdk.Duration.minutes(2),
      scalingSteps: [
        { upper: 0, change: -1 },
        { lower: 1, change: +1 },
        { lower: 10, change: +2 },
      ],
    });

    // ---------------------------------------------------------------- alarms
    const dlqDepth = new cloudwatch.Alarm(this, 'StageDlqDepth', {
      alarmDescription: 'Polycast: a stage message exhausted its retries (see runbooks)',
      metric: this.stageDeadLetterQueue.metricApproximateNumberOfMessagesVisible({
        period: cdk.Duration.minutes(1),
        statistic: 'Maximum',
      }),
      threshold: 0,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
      evaluationPeriods: 1,
      treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
    });
    const childFailed = new cloudwatch.Alarm(this, 'TargetJobExecutionsFailed', {
      alarmDescription: 'Polycast: a target-job execution failed',
      metric: this.childStateMachine.metricFailed({ period: cdk.Duration.minutes(5) }),
      threshold: 0,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
      evaluationPeriods: 1,
      treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
    });
    const parentFailed = new cloudwatch.Alarm(this, 'LocalizationJobExecutionsFailed', {
      alarmDescription: 'Polycast: a localization-job execution failed',
      metric: this.parentStateMachine.metricFailed({ period: cdk.Duration.minutes(5) }),
      threshold: 0,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
      evaluationPeriods: 1,
      treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
    });
    const reviewAge = new cloudwatch.Alarm(this, 'ReviewWaitAge', {
      alarmDescription: 'Polycast (info): a target has waited for review for more than 7 days',
      metric: this.reviewWaitQueue.metricApproximateAgeOfOldestMessage({
        period: cdk.Duration.hours(1),
        statistic: 'Maximum',
      }),
      threshold: cdk.Duration.days(7).toSeconds(),
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
      evaluationPeriods: 1,
      treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
    });
    for (const alarm of [dlqDepth, childFailed, parentFailed, reviewAge]) {
      alarm.addAlarmAction(alarmAction);
    }

    // ---------------------------------------------------------------- budget
    this.alertsTopic.addToResourcePolicy(
      new iam.PolicyStatement({
        sid: 'AllowBudgetsPublish',
        principals: [new iam.ServicePrincipal('budgets.amazonaws.com')],
        actions: ['sns:Publish'],
        resources: [this.alertsTopic.topicArn],
        conditions: { StringEquals: { 'aws:SourceAccount': this.account } },
      }),
    );
    new budgets.CfnBudget(this, 'MonthlyBudget', {
      budget: {
        budgetName: 'polycast-monthly',
        budgetType: 'COST',
        timeUnit: 'MONTHLY',
        budgetLimit: { amount: monthlyBudgetUsd, unit: 'USD' },
      },
      notificationsWithSubscribers: [80, 100].map((threshold) => ({
        notification: {
          notificationType: 'ACTUAL',
          comparisonOperator: 'GREATER_THAN',
          threshold,
          thresholdType: 'PERCENTAGE',
        },
        subscribers: [{ subscriptionType: 'SNS', address: this.alertsTopic.topicArn }],
      })),
    });

    // -------------------------------------------------------------- outputs
    new cdk.CfnOutput(this, 'SyncLabsSecretArn', {
      value: this.syncLabsSecret.secretArn,
      description:
        'Put the sync.so API key in field apiKey, then deploy with lipSyncProvider=synclabs',
    });
    new cdk.CfnOutput(this, 'EventBusName', { value: this.eventBus.eventBusName });
    new cdk.CfnOutput(this, 'StageQueueUrl', { value: this.stageQueue.queueUrl });
    new cdk.CfnOutput(this, 'ReviewWaitQueueUrl', { value: this.reviewWaitQueue.queueUrl });
    new cdk.CfnOutput(this, 'LocalizationJobStateMachineArn', {
      value: this.parentStateMachine.stateMachineArn,
    });
    new cdk.CfnOutput(this, 'TargetJobStateMachineArn', {
      value: this.childStateMachine.stateMachineArn,
    });
    new cdk.CfnOutput(this, 'AlertsTopicArn', {
      value: this.alertsTopic.topicArn,
      description: 'Subscribe an email address to receive alarm and budget notifications',
    });
  }
}
