-- Polycast Studio control-plane schema, milestone M1.
-- Every tenant table carries organization_id and is protected by row-level security that
-- reads app.org_id (set per transaction by the API). The application connects as
-- polycast_app, which is neither superuser nor table owner, so FORCE ROW LEVEL SECURITY applies.
-- Media time columns are bigint microseconds. Ids are UUID v7 generated by the API.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION app_org_id() RETURNS uuid
LANGUAGE sql STABLE AS $$
  SELECT NULLIF(current_setting('app.org_id', true), '')::uuid
$$;

CREATE OR REPLACE FUNCTION app_user_id() RETURNS uuid
LANGUAGE sql STABLE AS $$
  SELECT NULLIF(current_setting('app.user_id', true), '')::uuid
$$;

CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

-- Optimistic concurrency: bump version on every write of a versioned row.
CREATE OR REPLACE FUNCTION touch_versioned() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  NEW.version := COALESCE(OLD.version, 0) + 1;
  RETURN NEW;
END $$;

-- ---------------------------------------------------------------- identity (not tenant-scoped)
CREATE TABLE organizations (
  id uuid PRIMARY KEY,
  name text NOT NULL,
  plan text NOT NULL DEFAULT 'starter',
  region text NOT NULL DEFAULT 'us-east-1',
  retention_days integer NOT NULL DEFAULT 365,
  monthly_budget_cents integer,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'deleting')),
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE users (
  id uuid PRIMARY KEY,
  email text NOT NULL UNIQUE,
  display_name text NOT NULL,
  identity_subject text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE memberships (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  user_id uuid NOT NULL REFERENCES users (id),
  role text NOT NULL CHECK (role IN ('owner', 'admin', 'producer', 'reviewer', 'viewer')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id, user_id)
);
CREATE INDEX memberships_user_idx ON memberships (user_id);

-- ---------------------------------------------------------------- tenant tables
CREATE TABLE projects (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  title text NOT NULL,
  state text NOT NULL DEFAULT 'draft'
    CHECK (state IN ('draft', 'analyzing', 'ready', 'processing', 'complete', 'archived')),
  source_asset_id uuid,
  source_locale text,
  glossary_version_id uuid,
  owner_user_id uuid NOT NULL REFERENCES users (id),
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX projects_org_idx ON projects (organization_id, created_at DESC);

CREATE TABLE assets (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  project_id uuid NOT NULL REFERENCES projects (id),
  kind text NOT NULL,
  status text NOT NULL,
  storage_uri text NOT NULL,
  file_name text NOT NULL,
  content_type text NOT NULL,
  byte_size bigint NOT NULL,
  sha256 text,
  metadata jsonb,
  rejection jsonb,
  derived_from_asset_id uuid,
  retain_until timestamptz,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX assets_project_idx ON assets (organization_id, project_id);

CREATE TABLE uploads (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  project_id uuid NOT NULL REFERENCES projects (id),
  asset_id uuid NOT NULL REFERENCES assets (id),
  bucket text NOT NULL,
  object_key text NOT NULL,
  provider_upload_id text NOT NULL,
  part_size_bytes integer NOT NULL,
  part_count integer NOT NULL,
  byte_size bigint NOT NULL,
  file_name text NOT NULL,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'aborted')),
  parts jsonb NOT NULL DEFAULT '[]'::jsonb,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX uploads_project_idx ON uploads (organization_id, project_id, status);

CREATE TABLE speakers (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  project_id uuid NOT NULL REFERENCES projects (id),
  speaker_key text NOT NULL,
  label text NOT NULL,
  on_camera boolean NOT NULL DEFAULT false,
  sample_ranges jsonb NOT NULL DEFAULT '[]'::jsonb,
  voice_policy text NOT NULL DEFAULT 'stock'
    CHECK (voice_policy IN ('matched-synthetic', 'verified-replica', 'stock', 'keep-original')),
  consent_record_id uuid,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (project_id, speaker_key)
);

CREATE TABLE source_transcripts (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  project_id uuid NOT NULL REFERENCES projects (id),
  asset_id uuid NOT NULL REFERENCES assets (id),
  detected_locale text NOT NULL,
  detection_confidence real NOT NULL,
  confirmed_locale text,
  provider text NOT NULL,
  provider_version text NOT NULL,
  proxy_uri text,
  waveform_uri text,
  has_video boolean NOT NULL DEFAULT false,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX source_transcripts_project_idx ON source_transcripts (organization_id, project_id);

CREATE TABLE segments (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  transcript_id uuid NOT NULL REFERENCES source_transcripts (id),
  speaker_id uuid NOT NULL REFERENCES speakers (id),
  seq integer NOT NULL,
  start_us bigint NOT NULL CHECK (start_us >= 0),
  end_us bigint NOT NULL CHECK (end_us >= start_us),
  text text NOT NULL,
  language text NOT NULL,
  confidence real NOT NULL,
  words jsonb NOT NULL DEFAULT '[]'::jsonb,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (transcript_id, seq)
);

CREATE TABLE localization_jobs (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  project_id uuid NOT NULL REFERENCES projects (id),
  idempotency_key text NOT NULL,
  snapshot jsonb NOT NULL,
  state text NOT NULL,
  estimated_low_cents integer NOT NULL DEFAULT 0,
  estimated_high_cents integer NOT NULL DEFAULT 0,
  reserved_budget_cents integer NOT NULL DEFAULT 0,
  actual_cost_cents integer NOT NULL DEFAULT 0,
  rate_card_version text NOT NULL,
  started_at timestamptz,
  completed_at timestamptz,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id, idempotency_key)
);
CREATE INDEX localization_jobs_project_idx ON localization_jobs (organization_id, project_id, created_at DESC);

CREATE TABLE target_jobs (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  job_id uuid NOT NULL REFERENCES localization_jobs (id),
  project_id uuid NOT NULL REFERENCES projects (id),
  locale text NOT NULL,
  state text NOT NULL,
  approval_state text NOT NULL DEFAULT 'pending'
    CHECK (approval_state IN ('not-required', 'pending', 'approved', 'rejected')),
  lip_sync boolean NOT NULL DEFAULT false,
  provider_routes jsonb NOT NULL DEFAULT '{}'::jsonb,
  attempt integer NOT NULL DEFAULT 0,
  progress real NOT NULL DEFAULT 0,
  last_error text,
  /** Segment ids currently in scope for a partial re-run (null = all). */
  scope_segment_ids jsonb,
  package_version integer NOT NULL DEFAULT 0,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (job_id, locale)
);
CREATE INDEX target_jobs_org_state_idx ON target_jobs (organization_id, state);

CREATE TABLE translation_versions (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  target_job_id uuid NOT NULL REFERENCES target_jobs (id),
  segment_id uuid NOT NULL REFERENCES segments (id),
  source_segment_version integer NOT NULL,
  literal_text text,
  adapted_text text NOT NULL,
  timing_budget_us bigint NOT NULL,
  provider text NOT NULL,
  provider_version text NOT NULL,
  prompt_version text,
  confidence real NOT NULL,
  edited_by_user_id uuid,
  supersedes_id uuid REFERENCES translation_versions (id),
  generation integer NOT NULL DEFAULT 1,
  is_current boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX translation_versions_target_idx ON translation_versions (target_job_id, segment_id, is_current);

CREATE TABLE voice_assignments (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  target_job_id uuid NOT NULL REFERENCES target_jobs (id),
  speaker_id uuid NOT NULL REFERENCES speakers (id),
  voice_id text NOT NULL,
  provider text NOT NULL,
  policy text NOT NULL,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (target_job_id, speaker_id)
);

CREATE TABLE renders (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  target_job_id uuid NOT NULL REFERENCES target_jobs (id),
  kind text NOT NULL CHECK (kind IN ('speech', 'lipsync', 'mix', 'encode')),
  provider text NOT NULL,
  provider_version text NOT NULL,
  model_digest text,
  parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
  seed integer,
  input_asset_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  output_uri text,
  segment_id uuid REFERENCES segments (id),
  translation_version_id uuid REFERENCES translation_versions (id),
  start_us bigint,
  end_us bigint,
  measured_duration_us bigint,
  time_stretch_ratio real,
  voice_id text,
  stale boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX renders_target_idx ON renders (target_job_id, kind, stale);

CREATE TABLE qc_checks (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  target_job_id uuid NOT NULL REFERENCES target_jobs (id),
  run_no integer NOT NULL,
  metric text NOT NULL,
  threshold real,
  value real,
  passed boolean NOT NULL,
  provider text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX qc_checks_target_idx ON qc_checks (target_job_id, run_no);

CREATE TABLE qc_issues (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  qc_check_id uuid NOT NULL REFERENCES qc_checks (id),
  target_job_id uuid NOT NULL REFERENCES target_jobs (id),
  segment_id uuid REFERENCES segments (id),
  metric text NOT NULL,
  severity text NOT NULL CHECK (severity IN ('info', 'warning', 'critical')),
  start_us bigint,
  end_us bigint,
  evidence_asset_id uuid,
  recommendation text NOT NULL,
  resolution text NOT NULL DEFAULT 'open'
    CHECK (resolution IN ('open', 'accepted', 'regenerated', 'dismissed')),
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX qc_issues_target_idx ON qc_issues (target_job_id, resolution);

CREATE TABLE reviews (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  target_job_id uuid NOT NULL REFERENCES target_jobs (id),
  reviewer_user_id uuid NOT NULL REFERENCES users (id),
  scope text NOT NULL CHECK (scope IN ('segment', 'target')),
  segment_id uuid REFERENCES segments (id),
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE comments (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  target_job_id uuid NOT NULL REFERENCES target_jobs (id),
  segment_id uuid REFERENCES segments (id),
  author_user_id uuid NOT NULL REFERENCES users (id),
  body text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX comments_target_idx ON comments (target_job_id, created_at);

CREATE TABLE approvals (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  target_job_id uuid NOT NULL REFERENCES target_jobs (id),
  segment_id uuid REFERENCES segments (id),
  actor_user_id uuid NOT NULL REFERENCES users (id),
  decision text NOT NULL CHECK (decision IN ('approved', 'rejected')),
  /** The translation version approved; a regeneration invalidates approvals for that segment. */
  translation_version_id uuid REFERENCES translation_versions (id),
  artifact_version integer NOT NULL,
  stale boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX approvals_target_idx ON approvals (target_job_id, segment_id, stale);

CREATE TABLE deliverables (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  target_job_id uuid NOT NULL REFERENCES target_jobs (id),
  package_version integer NOT NULL,
  kind text NOT NULL,
  file_name text NOT NULL,
  content_type text NOT NULL,
  byte_size bigint NOT NULL,
  sha256 text NOT NULL,
  storage_uri text NOT NULL,
  ready boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX deliverables_target_idx ON deliverables (target_job_id, package_version);

CREATE TABLE provenance_manifests (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  target_job_id uuid NOT NULL REFERENCES target_jobs (id),
  package_version integer NOT NULL,
  manifest jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (target_job_id, package_version)
);

-- Append-only (BR-07). The app role gets INSERT/SELECT only.
CREATE TABLE audit_events (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  occurred_at timestamptz NOT NULL DEFAULT now(),
  actor_user_id uuid,
  action text NOT NULL,
  object_type text NOT NULL,
  object_id uuid NOT NULL,
  before_hash text,
  after_hash text,
  correlation_id text NOT NULL,
  ip_address text
);
CREATE INDEX audit_events_org_idx ON audit_events (organization_id, occurred_at DESC);

-- Outbox: every domain event is written here in the same transaction as the state change,
-- then NOTIFYed to SSE hubs. Tenant-scoped so clients only replay their own events.
CREATE TABLE domain_events (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  name text NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  correlation_id text NOT NULL,
  subject_type text NOT NULL,
  subject_id uuid NOT NULL,
  project_id uuid,
  payload jsonb NOT NULL,
  published_at timestamptz
);
CREATE INDEX domain_events_project_idx ON domain_events (organization_id, project_id, id);

CREATE TABLE idempotency_keys (
  organization_id uuid NOT NULL REFERENCES organizations (id),
  idem_key text NOT NULL,
  request_hash text NOT NULL,
  status_code integer,
  response jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (organization_id, idem_key)
);

-- ---------------------------------------------------------------- system tables (no RLS)
-- The work queue. Workers claim across tenants; results are applied inside tenant scope.
CREATE TABLE stage_tasks (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations (id),
  project_id uuid NOT NULL,
  job_id uuid,
  target_job_id uuid,
  asset_id uuid,
  stage text NOT NULL,
  attempt integer NOT NULL DEFAULT 1,
  idempotency_key text NOT NULL UNIQUE,
  correlation_id text NOT NULL,
  status text NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'claimed', 'succeeded', 'failed', 'cancelled')),
  not_before timestamptz NOT NULL DEFAULT now(),
  storage jsonb NOT NULL,
  parameters jsonb NOT NULL,
  claimed_by text,
  claimed_at timestamptz,
  lease_until timestamptz,
  result jsonb,
  error jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX stage_tasks_queue_idx ON stage_tasks (status, not_before, created_at);
CREATE INDEX stage_tasks_target_idx ON stage_tasks (target_job_id, status);

-- ---------------------------------------------------------------- triggers
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['organizations','projects','assets','uploads','speakers','source_transcripts',
    'segments','localization_jobs','target_jobs','voice_assignments','qc_issues','reviews']
  LOOP
    EXECUTE format('CREATE TRIGGER %I_touch BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION touch_versioned()', t, t);
  END LOOP;
  FOREACH t IN ARRAY ARRAY['users','memberships','deliverables','stage_tasks','renders']
  LOOP
    EXECUTE format('CREATE TRIGGER %I_touch BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION touch_updated_at()', t, t);
  END LOOP;
END $$;

-- ---------------------------------------------------------------- row-level security
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['projects','assets','uploads','speakers','source_transcripts','segments',
    'localization_jobs','target_jobs','translation_versions','voice_assignments','renders','qc_checks',
    'qc_issues','reviews','comments','approvals','deliverables','provenance_manifests','audit_events',
    'domain_events','idempotency_keys']
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (organization_id = app_org_id()) WITH CHECK (organization_id = app_org_id())', t);
  END LOOP;
END $$;

-- Memberships: visible within the current organization, or to the user they belong to
-- (so a signed-in user can list their organizations before choosing one).
ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE memberships FORCE ROW LEVEL SECURITY;
CREATE POLICY membership_visibility ON memberships
  USING (organization_id = app_org_id() OR user_id = app_user_id())
  WITH CHECK (organization_id = app_org_id() OR user_id = app_user_id());

-- ---------------------------------------------------------------- grants for the app role
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'polycast_app') THEN
    GRANT USAGE ON SCHEMA public TO polycast_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO polycast_app;
    REVOKE UPDATE, DELETE ON audit_events FROM polycast_app;
    REVOKE ALL ON schema_migrations FROM polycast_app;
    GRANT SELECT ON schema_migrations TO polycast_app;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO polycast_app;
  END IF;
END $$;
